### ISSUE TITLE
Could not load file or assembly 'System.Buffers, Version=4.0.2.0'

### ISSUE THREAD

**Issue by KoalaBear84** [nventive/HttpRecorder#7]
First, a big thanks!

## Expected Behavior
No assembly errors

## Actual Behavior
```
HttpRecorder.HttpRecorderException
  HResult=0x80131500
  Message=Error while writing file D:\Repositories\20200817_102908.har: Could not load file or assembly 'System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  Source=HttpRecorder
  StackTrace:
   at HttpRecorder.Repositories.HAR.HttpArchiveInteractionRepository.StoreAsync(Interaction interaction, CancellationToken cancellationToken)
   at HttpRecorder.HttpRecorderDelegatingHandler.<SendAsync>d__16.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NameSpaces.<GetDivisionsAsync>d__35.MoveNext() in D:\Repositories\File.cs:line 17

Inner Exception 1:
FileLoadException: Could not load file or assembly 'System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

## Steps to Reproduce the Problem

Good question. I have a project which I added HttpRecorder nuget, and a 

Project Host = .NET Framework 4.7.1
Project Lib (with HttpRecorder nuget/code) = .NET Standard 2.0
Tests project = .NET Framework 4.7.1

1. Running test which call HTTP code with HttpRecorder
2. Get error on first request

## Specifications

- Version: HttpRecorder 2.0.0
- Platform: Windows 10 Enterprise 1909
- Subsystem: ?

**Comment by KoalaBear84** [comment]
I do see that there are more issues, and it might have to do with .NET Framework vs .NET Standard..

https://github.com/dotnet/runtime/issues/1830

Although I have no idea how to fix/workaround it, if this is the case.

**Comment by KoalaBear84** [comment]
I love and hate .NET 🙃

Recreated the whole Tests project with .NET Framework, and now it works. But I guess the ticket needs to stay open until the underlying issue is solved, hopefully it is possibly with an extra hint in the project, maybe like set the System.Buffers version to 4.5.1 (the newest, which should have .NET Framework and .NET Standard versions).

Also for other users to see a possible workaround.
