### ISSUE TITLE
System.OutOfMemoryException

### ISSUE THREAD

**Issue by KoalaBear84** [nventive/HttpRecorder#8]
## Expected Behavior
Use streams instead of `File.WriteAllText` and `File.ReadAllText` on the following lines:
https://github.com/nventive/HttpRecorder/blob/master/HttpRecorder/Repositories/HAR/HttpArchiveInteractionRepository.cs#L40
https://github.com/nventive/HttpRecorder/blob/master/HttpRecorder/Repositories/HAR/HttpArchiveInteractionRepository.cs#L68

In this regard, JSON is a bad format, as you cannot append info, and need the whole object/thing in memory.

## Actual Behavior
```
   at System.Buffers.DefaultArrayPool`1.Rent(Int32 minimumLength)
   at System.Text.Json.PooledByteBufferWriter.CheckAndResizeBuffer(Int32 sizeHint)
   at System.Text.Json.PooledByteBufferWriter.GetMemory(Int32 sizeHint)
   at System.Text.Json.Utf8JsonWriter.Grow(Int32 requiredSize)
   at System.Text.Json.Utf8JsonWriter.WriteStringIndented(ReadOnlySpan`1 escapedValue)
   at System.Text.Json.Utf8JsonWriter.WriteStringByOptions(ReadOnlySpan`1 value)
   at System.Text.Json.Utf8JsonWriter.WriteStringEscapeValue(ReadOnlySpan`1 value, Int32 firstEscapeIndexVal)
   at System.Text.Json.Utf8JsonWriter.WriteStringValue(ReadOnlySpan`1 value)
   at System.Text.Json.Serialization.Converters.JsonConverterString.Write(Utf8JsonWriter writer, String value, JsonSerializerOptions options)
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnWrite(WriteStackFrame& current, Utf8JsonWriter writer)
   at System.Text.Json.JsonPropertyInfo.Write(WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.JsonSerializer.HandleObject(JsonPropertyInfo jsonPropertyInfo, JsonSerializerOptions options, Utf8JsonWriter writer, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteObject(JsonSerializerOptions options, Utf8JsonWriter writer, WriteStack& state)
   at System.Text.Json.JsonSerializer.Write(Utf8JsonWriter writer, Int32 originalWriterDepth, Int32 flushThreshold, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore(Utf8JsonWriter writer, PooledByteBufferWriter output, Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteCore(PooledByteBufferWriter output, Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteCoreString(Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at HttpRecorder.Repositories.HAR.HttpArchiveInteractionRepository.StoreAsync(Interaction interaction, CancellationToken cancellationToken)
   at HttpRecorder.HttpRecorderDelegatingHandler.<SendAsync>d__16.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Namespaces.<EnrichDivisionWithAssetsAsync>d__42.MoveNext() in D:\Repositories\File.cs:line 107
```

## Steps to Reproduce the Problem

1. Do some big requests

## Specifications

- Version: HttpRecorder 2.0.0
- Platform: Windows 10 Enterprise 1909
- Subsystem: ?

**Comment by KoalaBear84** [comment]
Wow.. I've tried to modify it locally, but I see that System.Text.Json is not yet fully ready, cannot find any clean code to read/write to streams with it like I do in Newtonsoft.

**Comment by KoalaBear84** [comment]
Hmm, I've rewritten it to use Newtonsoft with streams, but got stuck around the same part. Still might be a good idea to change it to streams, but thought it would make a bigger change. Now need to add some filtering..

**Comment by KoalaBear84** [comment]
I really don't know how the matcher should prevent any logging. Also tried to exclude all by this:
```csharp
RulesMatcher matcher = RulesMatcher.MatchMultiple.By((request, message) => false);

HttpClient = new HttpClient(new HttpRecorderDelegatingHandler($"{DateTime.UtcNow:yyyyMMdd_HHmmss}.har", matcher: matcher) { InnerHandler = new HttpClientHandler() })
{
    BaseAddress = new Uri(baseAddress),
};
```

But it will just log everything. Also tried MatchOnce. Do you have an example of real filtering?

**Comment by 0xced** [comment]
I just submitted #12 which might fix this issue. Using [JsonSerializer.SerializeAsync ](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer.serializeasync) that writes directly to a file stream should help reduce memory usage.

**Comment by danieliu456** [comment]
@0xced Awesome work! @julienblin can we get this merged and released somehow?

**Comment by sommmen** [comment]
@julienblinnv @julienblin Hiya are you still maintaining this project, and if so would you look at the open prs?

**Comment by sommmen** [comment]
> @julienblinnv @julienblin Hiya are you still maintaining this project, and if so would you look at the open prs?

Seems the guy is no longer working with the company NVentive anymore.

@jeanplevesque @MatFillion @vincentcastagna Hiya, would any of you care to take a look at some of the community contributions and provide some support regarding maintaining this repo?

**Comment by jeanplevesque** [comment]
PR looks good to me.
I'll also poke @nventive/backend-maintainers
